config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :feeds
  resources :articles

  root to: 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :feed, foreign_key: :feed_id

  validates :title, :link, :published_at, :description, presence: true
end

app/models/feed.rb
class Feed < ApplicationRecord
  has_many :articles, dependent: :destroy

  validates :url, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.order(:published_at)
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController

  def new
    @feed = Feed.new
  end

  def create
    @feed = Feed.new feed_params
    if @feed.save
      redirect_to feeds_path
    else
      render action: :new
    end
  end

  def edit
    @feed = Feed.find_by(id: params[:id])
    unless @feed
      render action: :index
    end
  end

  def update
    @feed = Feed.find_by(id: params[:id])
    if @feed && @feed.update_attributes(feed_params)
      redirect_to feeds_path
    else
      render action: :edit
    end
  end

  def index
    @feeds = Feed.all
  end

  def destroy
    @feed = Feed.find_by(id: params[:id])
    unless @feed && @feed.destroy
      @feeds = Feed.all
      render action: :index
    end
  end

  private

    def feed_params
      params.require(:feed).permit(:url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/articles/index.html.haml
%div{ class: 'row' }
  %h3{ class: 'text-center' }
    Articles
%div{ class: 'row' }
  %div{ class: 'col-md-2 pull-right' }
    = link_to 'Go to Feeds', feeds_path, class: 'btn-sm btn-primary'
%table{ class: 'table' }
  %thead
    %tr
      %th
        Title
  %tbody
    - @articles.each do |article|
      %tr
        %td
          = link_to article.title, article.link, target: :_blank

app/views/feeds/_form.html.haml
- if @feed.errors.any?
  %div{ class: 'well' }
    %h4
      Errors
    %ul
      - @feed.errors.full_messages.each do |message|
        %li
          = message

= form_for @feed, class: 'form-horizontal' do |f|
  %div{ class: 'form-group' }
    %div{ class: 'col-md-2' }
      = f.label :url
    %div{ class: 'col-md-6' }
      = f.text_field :url, class: 'form-control', placeholder: 'Enter URL'
  %div{ class: 'form-group' }
    %div{ class: 'col-md-8' }
      = f.submit

app/views/feeds/destroy.js.erb
$("tr#feed-<%= @feed.id %>").remove();

app/views/feeds/edit.html.haml
= render partial: 'form'

app/views/feeds/index.html.haml
%div{ class: 'row' }
  %h3{ class: 'text-center' }
    Feeds
%div{ class: 'row' }
  %div{ class: 'col-md-2 pull-right' }
    = link_to 'Add New', new_feed_path, class: 'btn-sm btn-primary'
  %div{ class: 'col-md-2 pull-right' }
    = link_to 'Go to Articles', root_path, class: 'btn-sm btn-primary'
%table{ class: 'table' }
  %thead
    %tr
      %th
        URL
      %th
      %th
  %tbody
    - @feeds.each do |feed|
      %tr{ id: "feed-#{feed.id}" }
        %td
          = link_to feed.url, target: :_blank
        %td
          = link_to 'Edit', edit_feed_path(feed.id)
        %td
          = link_to 'Delete', feed_path(feed.id), { remote: true, method: :delete }

app/views/feeds/new.html.haml
= render partial: 'form'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RssReader</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>